### ISSUE TITLE
Add endpoints for multiple leagues

### ISSUE THREAD

**Issue by mattikus** [splewis/csgo-motw#2]
Instead of simply having only a single default league, allow multiple leagues to be configured to check or return and have an endpoint for each:

.e.g: `https://csgo-motw.appspot.com/esea` or `https://csgo-motw.appspot.com/cevo`

**Comment by mattikus** [comment]
I see now that the default URL allows parameter selection. I think the default page should show all info and selection of each league should be based on a URL path.

**Comment by splewis** [comment]
I'd rather keep it as a url param so adding a different league doesn't require a change of url, only a change of the params on a request.
